packages:
  - packages/*

ignoredBuiltDependencies:
  - bcrypt
  - electron
  - esbuild
  - protobufjs
  - puppeteer

onlyBuiltDependencies:
  - '@ffmpeg-installer/ffmpeg'
  - onnxruntime-node
  - sharp
